[build]
  command = "pnpm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "pnpm run dev"
  targetPort = 5173
  framework = "#custom"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

